// Package seed inserts demo users (with encrypted email) and their reviews on
// startup for non-production environments. These can no longer live in seed.sql
// because email is AES-GCM encrypted in-app — SQL can't produce the ciphertext.
// Products/categories/brands are still seeded via migrations/seed.sql.
package seed

import (
	"context"
	"log"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"

	"gitea.kood.tech/ibrahimsen/i-love-shopping/internal/crypto"
)

type demoUser struct {
	id, email, hash, role string
}

// bcrypt hashes match the previous seed.sql accounts (admin/customer logins).
var demoUsers = []demoUser{
	{"a0000000-0000-0000-0000-000000000001", "admin@shop.com", "$2b$10$eoPLJ/PW4skcSOuKY0lcuuegPRmubIawIrDGyByoK8yzn.sSGY9Qq", "admin"},
	{"c0000000-0000-0000-0000-000000000001", "customer@shop.com", "$2b$10$/ieJ0h2MEnPkr/TH9zhvpOVZ01GS2biGBUNZ1JMspSmBiwUOhxgxG", "customer"},
	{"c0000000-0000-0000-0000-000000000003", "test3@test.com", "$2b$10$Y9YIZzIkLNOoYRZ.oECeKOd0efN4Tpkzp.vRv7F3xNrTBB7ilgUZG", "customer"},
}

type demoReview struct {
	userID, productID, comment string
	rating                     int
}

// demoReviews lives in reviews_gen.go (generated by scripts/gen-seed.mjs) so the
// reviews always reference the generated catalogue's product IDs.

// Demo seeds demo users + reviews. Idempotent (ON CONFLICT DO NOTHING). Best
// effort: a single failing row (e.g. a missing product FK in host-only dev) is
// logged and skipped rather than aborting startup.
func Demo(ctx context.Context, db *pgxpool.Pool, enc *crypto.Encryptor) {
	for _, u := range demoUsers {
		email := strings.ToLower(strings.TrimSpace(u.email))
		encEmail, err := enc.Encrypt(email)
		if err != nil {
			log.Printf("seed: encrypt %s: %v", u.email, err)
			continue
		}
		if _, err := db.Exec(ctx,
			`INSERT INTO users (id, email_encrypted, email_hmac, password_hash, role)
			 VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING`,
			u.id, encEmail, enc.HMAC(email), u.hash, u.role); err != nil {
			log.Printf("seed: user %s: %v", u.email, err)
		}
	}

	for _, rv := range demoReviews {
		if _, err := db.Exec(ctx,
			`INSERT INTO reviews (user_id, product_id, rating, comment, status)
			 VALUES ($1, $2, $3, $4, 'approved') ON CONFLICT (user_id, product_id) DO NOTHING`,
			rv.userID, rv.productID, rv.rating, rv.comment); err != nil {
			log.Printf("seed: review for %s: %v", rv.productID, err)
		}
	}
}
